# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x0cgrpc_project\"!\n\x0eRequestMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"#\n\x0fResponseMessage\x12\x10\n\x08response\x18\x01 \x01(\t2[\n\rTargetService\x12J\n\x0bSendRequest\x12\x1c.grpc_project.RequestMessage\x1a\x1d.grpc_project.ResponseMessageB\x14Z\x12grpc_project/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022grpc_project/proto'
  _globals['_REQUESTMESSAGE']._serialized_start=31
  _globals['_REQUESTMESSAGE']._serialized_end=64
  _globals['_RESPONSEMESSAGE']._serialized_start=66
  _globals['_RESPONSEMESSAGE']._serialized_end=101
  _globals['_TARGETSERVICE']._serialized_start=103
  _globals['_TARGETSERVICE']._serialized_end=194
# @@protoc_insertion_point(module_scope)
